# Generated by Django 4.1.4 on 2023-01-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_book',
            name='End_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='Start_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stud_Phno',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stud_Sem',
            field=models.CharField(max_length=50),
        ),
    ]
